#!/usr/bin/expect
set timeout 20
set cmd [lrange $argv 5 end]
set password [lindex $argv 0]
set tutu [lrange $argv 1 3]
set ex [lindex $argv 4]
eval spawn $cmd
expect "assword:"
send "$password\r\n";
expect "# "
send "$tutu\r\n"
expect "# "
send "$ex\r\n"
interact
